import "./globals.css";

import Bgdaynamic from "@/daynamicbaclGround/Bgdaynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Bgdaynamic>{children}</Bgdaynamic>
      </body>
    </html>
  );
}
